<?php

/* 
 * Country name list, with dialling code 
 */

function get_country_list_all(){
	$cnlwdc = array(
		'AFG' => [ 'name' => "Afghanistan", 'phone' => '93', 'iso2' => 'AF', 'iso3' => 'AFG' ],
		'ALB' => [ 'name' => "Albania", 'phone' => '355', 'iso2' => 'AL', 'iso3' => 'ALB' ],
		'DZA' => [ 'name' => "Algeria", 'phone' => '213', 'iso2' => 'DZ', 'iso3' => 'DZA' ],
		'ASM' => [ 'name' => "American Samoa", 'phone' => '1-684', 'iso2' => 'AS', 'iso3' => 'ASM' ],
		'AND' => [ 'name' => "Andorra", 'phone' => '376', 'iso2' => 'AD', 'iso3' => 'AND' ],
		'AGO' => [ 'name' => "Angola", 'phone' => '244', 'iso2' => 'AO', 'iso3' => 'AGO' ],
		'AIA' => [ 'name' => "Anguilla", 'phone' => '1-264', 'iso2' => 'AI', 'iso3' => 'AIA' ],
		'ATA' => [ 'name' => "Antarctica", 'phone' => '672', 'iso2' => 'AQ', 'iso3' => 'ATA' ],
		'ATG' => [ 'name' => "Antigua and Barbuda", 'phone' => '1-268', 'iso2' => 'AG', 'iso3' => 'ATG' ],
		'ARG' => [ 'name' => "Argentina", 'phone' => '54', 'iso2' => 'AR', 'iso3' => 'ARG' ],
		'ARM' => [ 'name' => "Armenia", 'phone' => '374', 'iso2' => 'AM', 'iso3' => 'ARM' ],
		'ABW' => [ 'name' => "Aruba", 'phone' => '297', 'iso2' => 'AW', 'iso3' => 'ABW' ],
		'AUS' => [ 'name' => "Australia", 'phone' => '61', 'iso2' => 'AU', 'iso3' => 'AUS' ],
		'AUT' => [ 'name' => "Austria", 'phone' => '43', 'iso2' => 'AT', 'iso3' => 'AUT' ],
		'AZE' => [ 'name' => "Azerbaijan", 'phone' => '994', 'iso2' => 'AZ', 'iso3' => 'AZE' ],
		'BHS' => [ 'name' => "Bahamas", 'phone' => '1-242', 'iso2' => 'BS', 'iso3' => 'BHS' ],
		'BHR' => [ 'name' => "Bahrain", 'phone' => '973', 'iso2' => 'BH', 'iso3' => 'BHR' ],
		'BGD' => [ 'name' => "Bangladesh", 'phone' => '880', 'iso2' => 'BD', 'iso3' => 'BGD' ],
		'BRB' => [ 'name' => "Barbados", 'phone' => '1-246', 'iso2' => 'BB', 'iso3' => 'BRB' ],
		'BLR' => [ 'name' => "Belarus", 'phone' => '375', 'iso2' => 'BY', 'iso3' => 'BLR' ],
		'BEL' => [ 'name' => "Belgium", 'phone' => '32', 'iso2' => 'BE', 'iso3' => 'BEL' ],
		'BLZ' => [ 'name' => "Belize", 'phone' => '501', 'iso2' => 'BZ', 'iso3' => 'BLZ' ],
		'BEN' => [ 'name' => "Benin", 'phone' => '229', 'iso2' => 'BJ', 'iso3' => 'BEN' ],
		'BMU' => [ 'name' => "Bermuda", 'phone' => '1-441', 'iso2' => 'BM', 'iso3' => 'BMU' ],
		'BTN' => [ 'name' => "Bhutan", 'phone' => '975', 'iso2' => 'BT', 'iso3' => 'BTN' ],
		'BOL' => [ 'name' => "Bolivia", 'phone' => '591', 'iso2' => 'BO', 'iso3' => 'BOL' ],
		'BIH' => [ 'name' => "Bosnia and Herzegovina", 'phone' => '387', 'iso2' => 'BA', 'iso3' => 'BIH' ],
		'BWA' => [ 'name' => "Botswana", 'phone' => '267', 'iso2' => 'BW', 'iso3' => 'BWA' ],
		'BRA' => [ 'name' => "Brazil", 'phone' => '55', 'iso2' => 'BR', 'iso3' => 'BRA' ],
		'IOT' => [ 'name' => "British Indian Ocean Territory", 'phone' => '246', 'iso2' => 'IO', 'iso3' => 'IOT' ],
		'VGB' => [ 'name' => "British Virgin Islands", 'phone' => '1-284', 'iso2' => 'VG', 'iso3' => 'VGB' ],
		'BRN' => [ 'name' => "Brunei", 'phone' => '673', 'iso2' => 'BN', 'iso3' => 'BRN' ],
		'BGR' => [ 'name' => "Bulgaria", 'phone' => '359', 'iso2' => 'BG', 'iso3' => 'BGR' ],
		'BFA' => [ 'name' => "Burkina Faso", 'phone' => '226', 'iso2' => 'BF', 'iso3' => 'BFA' ],
		'BDI' => [ 'name' => "Burundi", 'phone' => '257', 'iso2' => 'BI', 'iso3' => 'BDI' ],
		'KHM' => [ 'name' => "Cambodia", 'phone' => '855', 'iso2' => 'KH', 'iso3' => 'KHM' ],
		'CMR' => [ 'name' => "Cameroon", 'phone' => '237', 'iso2' => 'CM', 'iso3' => 'CMR' ],
		'CAN' => [ 'name' => "Canada", 'phone' => '1', 'iso2' => 'CA', 'iso3' => 'CAN' ],
		'CPV' => [ 'name' => "Cape Verde", 'phone' => '238', 'iso2' => 'CV', 'iso3' => 'CPV' ],
		'CYM' => [ 'name' => "Cayman Islands", 'phone' => '1-345', 'iso2' => 'KY', 'iso3' => 'CYM' ],
		'CAF' => [ 'name' => "Central African Republic", 'phone' => '236', 'iso2' => 'CF', 'iso3' => 'CAF' ],
		'TCD' => [ 'name' => "Chad", 'phone' => '235', 'iso2' => 'TD', 'iso3' => 'TCD' ],
		'CHL' => [ 'name' => "Chile", 'phone' => '56', 'iso2' => 'CL', 'iso3' => 'CHL' ],
		'CHN' => [ 'name' => "China", 'phone' => '86', 'iso2' => 'CN', 'iso3' => 'CHN' ],
		'CXR' => [ 'name' => "Christmas Island", 'phone' => '61', 'iso2' => 'CX', 'iso3' => 'CXR' ],
		'CCK' => [ 'name' => "Cocos Islands", 'phone' => '61', 'iso2' => 'CC', 'iso3' => 'CCK' ],
		'COL' => [ 'name' => "Colombia", 'phone' => '57', 'iso2' => 'CO', 'iso3' => 'COL' ],
		'COM' => [ 'name' => "Comoros", 'phone' => '269', 'iso2' => 'KM', 'iso3' => 'COM' ],
		'COK' => [ 'name' => "Cook Islands", 'phone' => '682', 'iso2' => 'CK', 'iso3' => 'COK' ],
		'CRI' => [ 'name' => "Costa Rica", 'phone' => '506', 'iso2' => 'CR', 'iso3' => 'CRI' ],
		'HRV' => [ 'name' => "Croatia", 'phone' => '385', 'iso2' => 'HR', 'iso3' => 'HRV' ],
		'CUB' => [ 'name' => "Cuba", 'phone' => '53', 'iso2' => 'CU', 'iso3' => 'CUB' ],
		'CUW' => [ 'name' => "Curacao", 'phone' => '599', 'iso2' => 'CW', 'iso3' => 'CUW' ],
		'CYP' => [ 'name' => "Cyprus", 'phone' => '357', 'iso2' => 'CY', 'iso3' => 'CYP' ],
		'CZE' => [ 'name' => "Czech Republic", 'phone' => '420', 'iso2' => 'CZ', 'iso3' => 'CZE' ],
		'COD' => [ 'name' => "Democratic Republic of the Congo", 'phone' => '243', 'iso2' => 'CD', 'iso3' => 'COD' ],
		'DNK' => [ 'name' => "Denmark", 'phone' => '45', 'iso2' => 'DK', 'iso3' => 'DNK' ],
		'DJI' => [ 'name' => "Djibouti", 'phone' => '253', 'iso2' => 'DJ', 'iso3' => 'DJI' ],
		'DMA' => [ 'name' => "Dominica", 'phone' => '1-767', 'iso2' => 'DM', 'iso3' => 'DMA' ],
		'DOM' => [ 'name' => "Dominican Republic", 'phone' => '1-809, 1-829, 1-849', 'iso2' => 'DO', 'iso3' => 'DOM' ],
		'TLS' => [ 'name' => "East Timor", 'phone' => '670', 'iso2' => 'TL', 'iso3' => 'TLS' ],
		'ECU' => [ 'name' => "Ecuador", 'phone' => '593', 'iso2' => 'EC', 'iso3' => 'ECU' ],
		'EGY' => [ 'name' => "Egypt", 'phone' => '20', 'iso2' => 'EG', 'iso3' => 'EGY' ],
		'SLV' => [ 'name' => "El Salvador", 'phone' => '503', 'iso2' => 'SV', 'iso3' => 'SLV' ],
		'GNQ' => [ 'name' => "Equatorial Guinea", 'phone' => '240', 'iso2' => 'GQ', 'iso3' => 'GNQ' ],
		'ERI' => [ 'name' => "Eritrea", 'phone' => '291', 'iso2' => 'ER', 'iso3' => 'ERI' ],
		'EST' => [ 'name' => "Estonia", 'phone' => '372', 'iso2' => 'EE', 'iso3' => 'EST' ],
		'ETH' => [ 'name' => "Ethiopia", 'phone' => '251', 'iso2' => 'ET', 'iso3' => 'ETH' ],
		'FLK' => [ 'name' => "Falkland Islands", 'phone' => '500', 'iso2' => 'FK', 'iso3' => 'FLK' ],
		'FRO' => [ 'name' => "Faroe Islands", 'phone' => '298', 'iso2' => 'FO', 'iso3' => 'FRO' ],
		'FJI' => [ 'name' => "Fiji", 'phone' => '679', 'iso2' => 'FJ', 'iso3' => 'FJI' ],
		'FIN' => [ 'name' => "Finland", 'phone' => '358', 'iso2' => 'FI', 'iso3' => 'FIN' ],
		'FRA' => [ 'name' => "France", 'phone' => '33', 'iso2' => 'FR', 'iso3' => 'FRA' ],
		'PYF' => [ 'name' => "French Polynesia", 'phone' => '689', 'iso2' => 'PF', 'iso3' => 'PYF' ],
		'GAB' => [ 'name' => "Gabon", 'phone' => '241', 'iso2' => 'GA', 'iso3' => 'GAB' ],
		'GMB' => [ 'name' => "Gambia", 'phone' => '220', 'iso2' => 'GM', 'iso3' => 'GMB' ],
		'GEO' => [ 'name' => "Georgia", 'phone' => '995', 'iso2' => 'GE', 'iso3' => 'GEO' ],
		'DEU' => [ 'name' => "Germany", 'phone' => '49', 'iso2' => 'DE', 'iso3' => 'DEU' ],
		'GHA' => [ 'name' => "Ghana", 'phone' => '233', 'iso2' => 'GH', 'iso3' => 'GHA' ],
		'GIB' => [ 'name' => "Gibraltar", 'phone' => '350', 'iso2' => 'GI', 'iso3' => 'GIB' ],
		'GRC' => [ 'name' => "Greece", 'phone' => '30', 'iso2' => 'GR', 'iso3' => 'GRC' ],
		'GRL' => [ 'name' => "Greenland", 'phone' => '299', 'iso2' => 'GL', 'iso3' => 'GRL' ],
		'GRD' => [ 'name' => "Grenada", 'phone' => '1-473', 'iso2' => 'GD', 'iso3' => 'GRD' ],
		'GUM' => [ 'name' => "Guam", 'phone' => '1-671', 'iso2' => 'GU', 'iso3' => 'GUM' ],
		'GTM' => [ 'name' => "Guatemala", 'phone' => '502', 'iso2' => 'GT', 'iso3' => 'GTM' ],
		'GGY' => [ 'name' => "Guernsey", 'phone' => '44-1481', 'iso2' => 'GG', 'iso3' => 'GGY' ],
		'GIN' => [ 'name' => "Guinea", 'phone' => '224', 'iso2' => 'GN', 'iso3' => 'GIN' ],
		'GNB' => [ 'name' => "Guinea-Bissau", 'phone' => '245', 'iso2' => 'GW', 'iso3' => 'GNB' ],
		'GUY' => [ 'name' => "Guyana", 'phone' => '592', 'iso2' => 'GY', 'iso3' => 'GUY' ],
		'HTI' => [ 'name' => "Haiti", 'phone' => '509', 'iso2' => 'HT', 'iso3' => 'HTI' ],
		'HND' => [ 'name' => "Honduras", 'phone' => '504', 'iso2' => 'HN', 'iso3' => 'HND' ],
		'HKG' => [ 'name' => "Hong Kong", 'phone' => '852', 'iso2' => 'HK', 'iso3' => 'HKG' ],
		'HUN' => [ 'name' => "Hungary", 'phone' => '36', 'iso2' => 'HU', 'iso3' => 'HUN' ],
		'ISL' => [ 'name' => "Iceland", 'phone' => '354', 'iso2' => 'IS', 'iso3' => 'ISL' ],
		'IND' => [ 'name' => "India", 'phone' => '91', 'iso2' => 'IN', 'iso3' => 'IND' ],
		'IDN' => [ 'name' => "Indonesia", 'phone' => '62', 'iso2' => 'ID', 'iso3' => 'IDN' ],
		'IRN' => [ 'name' => "Iran", 'phone' => '98', 'iso2' => 'IR', 'iso3' => 'IRN' ],
		'IRQ' => [ 'name' => "Iraq", 'phone' => '964', 'iso2' => 'IQ', 'iso3' => 'IRQ' ],
		'IRL' => [ 'name' => "Ireland", 'phone' => '353', 'iso2' => 'IE', 'iso3' => 'IRL' ],
		'IMN' => [ 'name' => "Isle of Man", 'phone' => '44-1624', 'iso2' => 'IM', 'iso3' => 'IMN' ],
		'ISR' => [ 'name' => "Israel", 'phone' => '972', 'iso2' => 'IL', 'iso3' => 'ISR' ],
		'ITA' => [ 'name' => "Italy", 'phone' => '39', 'iso2' => 'IT', 'iso3' => 'ITA' ],
		'CIV' => [ 'name' => "Ivory Coast", 'phone' => '225', 'iso2' => 'CI', 'iso3' => 'CIV' ],
		'JAM' => [ 'name' => "Jamaica", 'phone' => '1-876', 'iso2' => 'JM', 'iso3' => 'JAM' ],
		'JPN' => [ 'name' => "Japan", 'phone' => '81', 'iso2' => 'JP', 'iso3' => 'JPN' ],
		'JEY' => [ 'name' => "Jersey", 'phone' => '44-1534', 'iso2' => 'JE', 'iso3' => 'JEY' ],
		'JOR' => [ 'name' => "Jordan", 'phone' => '962', 'iso2' => 'JO', 'iso3' => 'JOR' ],
		'KAZ' => [ 'name' => "Kazakhstan", 'phone' => '7', 'iso2' => 'KZ', 'iso3' => 'KAZ' ],
		'KEN' => [ 'name' => "Kenya", 'phone' => '254', 'iso2' => 'KE', 'iso3' => 'KEN' ],
		'KIR' => [ 'name' => "Kiribati", 'phone' => '686', 'iso2' => 'KI', 'iso3' => 'KIR' ],
		'XKX' => [ 'name' => "Kosovo", 'phone' => '383', 'iso2' => 'XK', 'iso3' => 'XKX' ],
		'KWT' => [ 'name' => "Kuwait", 'phone' => '965', 'iso2' => 'KW', 'iso3' => 'KWT' ],
		'KGZ' => [ 'name' => "Kyrgyzstan", 'phone' => '996', 'iso2' => 'KG', 'iso3' => 'KGZ' ],
		'LAO' => [ 'name' => "Laos", 'phone' => '856', 'iso2' => 'LA', 'iso3' => 'LAO' ],
		'LVA' => [ 'name' => "Latvia", 'phone' => '371', 'iso2' => 'LV', 'iso3' => 'LVA' ],
		'LBN' => [ 'name' => "Lebanon", 'phone' => '961', 'iso2' => 'LB', 'iso3' => 'LBN' ],
		'LSO' => [ 'name' => "Lesotho", 'phone' => '266', 'iso2' => 'LS', 'iso3' => 'LSO' ],
		'LBR' => [ 'name' => "Liberia", 'phone' => '231', 'iso2' => 'LR', 'iso3' => 'LBR' ],
		'LBY' => [ 'name' => "Libya", 'phone' => '218', 'iso2' => 'LY', 'iso3' => 'LBY' ],
		'LIE' => [ 'name' => "Liechtenstein", 'phone' => '423', 'iso2' => 'LI', 'iso3' => 'LIE' ],
		'LTU' => [ 'name' => "Lithuania", 'phone' => '370', 'iso2' => 'LT', 'iso3' => 'LTU' ],
		'LUX' => [ 'name' => "Luxembourg", 'phone' => '352', 'iso2' => 'LU', 'iso3' => 'LUX' ],
		'MAC' => [ 'name' => "Macau", 'phone' => '853', 'iso2' => 'MO', 'iso3' => 'MAC' ],
		'MKD' => [ 'name' => "Macedonia", 'phone' => '389', 'iso2' => 'MK', 'iso3' => 'MKD' ],
		'MDG' => [ 'name' => "Madagascar", 'phone' => '261', 'iso2' => 'MG', 'iso3' => 'MDG' ],
		'MWI' => [ 'name' => "Malawi", 'phone' => '265', 'iso2' => 'MW', 'iso3' => 'MWI' ],
		'MYS' => [ 'name' => "Malaysia", 'phone' => '60', 'iso2' => 'MY', 'iso3' => 'MYS' ],
		'MDV' => [ 'name' => "Maldives", 'phone' => '960', 'iso2' => 'MV', 'iso3' => 'MDV' ],
		'MLI' => [ 'name' => "Mali", 'phone' => '223', 'iso2' => 'ML', 'iso3' => 'MLI' ],
		'MLT' => [ 'name' => "Malta", 'phone' => '356', 'iso2' => 'MT', 'iso3' => 'MLT' ],
		'MHL' => [ 'name' => "Marshall Islands", 'phone' => '692', 'iso2' => 'MH', 'iso3' => 'MHL' ],
		'MRT' => [ 'name' => "Mauritania", 'phone' => '222', 'iso2' => 'MR', 'iso3' => 'MRT' ],
		'MUS' => [ 'name' => "Mauritius", 'phone' => '230', 'iso2' => 'MU', 'iso3' => 'MUS' ],
		'MYT' => [ 'name' => "Mayotte", 'phone' => '262', 'iso2' => 'YT', 'iso3' => 'MYT' ],
		'MEX' => [ 'name' => "Mexico", 'phone' => '52', 'iso2' => 'MX', 'iso3' => 'MEX' ],
		'FSM' => [ 'name' => "Micronesia", 'phone' => '691', 'iso2' => 'FM', 'iso3' => 'FSM' ],
		'MDA' => [ 'name' => "Moldova", 'phone' => '373', 'iso2' => 'MD', 'iso3' => 'MDA' ],
		'MCO' => [ 'name' => "Monaco", 'phone' => '377', 'iso2' => 'MC', 'iso3' => 'MCO' ],
		'MNG' => [ 'name' => "Mongolia", 'phone' => '976', 'iso2' => 'MN', 'iso3' => 'MNG' ],
		'MNE' => [ 'name' => "Montenegro", 'phone' => '382', 'iso2' => 'ME', 'iso3' => 'MNE' ],
		'MSR' => [ 'name' => "Montserrat", 'phone' => '1-664', 'iso2' => 'MS', 'iso3' => 'MSR' ],
		'MAR' => [ 'name' => "Morocco", 'phone' => '212', 'iso2' => 'MA', 'iso3' => 'MAR' ],
		'MOZ' => [ 'name' => "Mozambique", 'phone' => '258', 'iso2' => 'MZ', 'iso3' => 'MOZ' ],
		'MMR' => [ 'name' => "Myanmar", 'phone' => '95', 'iso2' => 'MM', 'iso3' => 'MMR' ],
		'NAM' => [ 'name' => "Namibia", 'phone' => '264', 'iso2' => 'NA', 'iso3' => 'NAM' ],
		'NRU' => [ 'name' => "Nauru", 'phone' => '674', 'iso2' => 'NR', 'iso3' => 'NRU' ],
		'NPL' => [ 'name' => "Nepal", 'phone' => '977', 'iso2' => 'NP', 'iso3' => 'NPL' ],
		'NLD' => [ 'name' => "Netherlands", 'phone' => '31', 'iso2' => 'NL', 'iso3' => 'NLD' ],
		'ANT' => [ 'name' => "Netherlands Antilles", 'phone' => '599', 'iso2' => 'AN', 'iso3' => 'ANT' ],
		'NCL' => [ 'name' => "New Caledonia", 'phone' => '687', 'iso2' => 'NC', 'iso3' => 'NCL' ],
		'NZL' => [ 'name' => "New Zealand", 'phone' => '64', 'iso2' => 'NZ', 'iso3' => 'NZL' ],
		'NIC' => [ 'name' => "Nicaragua", 'phone' => '505', 'iso2' => 'NI', 'iso3' => 'NIC' ],
		'NER' => [ 'name' => "Niger", 'phone' => '227', 'iso2' => 'NE', 'iso3' => 'NER' ],
		'NGA' => [ 'name' => "Nigeria", 'phone' => '234', 'iso2' => 'NG', 'iso3' => 'NGA' ],
		'NIU' => [ 'name' => "Niue", 'phone' => '683', 'iso2' => 'NU', 'iso3' => 'NIU' ],
		'PRK' => [ 'name' => "North Korea", 'phone' => '850', 'iso2' => 'KP', 'iso3' => 'PRK' ],
		'MNP' => [ 'name' => "Northern Mariana Islands", 'phone' => '1-670', 'iso2' => 'MP', 'iso3' => 'MNP' ],
		'NOR' => [ 'name' => "Norway", 'phone' => '47', 'iso2' => 'NO', 'iso3' => 'NOR' ],
		'OMN' => [ 'name' => "Oman", 'phone' => '968', 'iso2' => 'OM', 'iso3' => 'OMN' ],
		'PAK' => [ 'name' => "Pakistan", 'phone' => '92', 'iso2' => 'PK', 'iso3' => 'PAK' ],
		'PLW' => [ 'name' => "Palau", 'phone' => '680', 'iso2' => 'PW', 'iso3' => 'PLW' ],
		'PSE' => [ 'name' => "Palestine", 'phone' => '970', 'iso2' => 'PS', 'iso3' => 'PSE' ],
		'PAN' => [ 'name' => "Panama", 'phone' => '507', 'iso2' => 'PA', 'iso3' => 'PAN' ],
		'PNG' => [ 'name' => "Papua New Guinea", 'phone' => '675', 'iso2' => 'PG', 'iso3' => 'PNG' ],
		'PRY' => [ 'name' => "Paraguay", 'phone' => '595', 'iso2' => 'PY', 'iso3' => 'PRY' ],
		'PER' => [ 'name' => "Peru", 'phone' => '51', 'iso2' => 'PE', 'iso3' => 'PER' ],
		'PHL' => [ 'name' => "Philippines", 'phone' => '63', 'iso2' => 'PH', 'iso3' => 'PHL' ],
		'PCN' => [ 'name' => "Pitcairn", 'phone' => '64', 'iso2' => 'PN', 'iso3' => 'PCN' ],
		'POL' => [ 'name' => "Poland", 'phone' => '48', 'iso2' => 'PL', 'iso3' => 'POL' ],
		'PRT' => [ 'name' => "Portugal", 'phone' => '351', 'iso2' => 'PT', 'iso3' => 'PRT' ],
		'PRI' => [ 'name' => "Puerto Rico", 'phone' => '1-787, 1-939', 'iso2' => 'PR', 'iso3' => 'PRI' ],
		'QAT' => [ 'name' => "Qatar", 'phone' => '974', 'iso2' => 'QA', 'iso3' => 'QAT' ],
		'COG' => [ 'name' => "Republic of the Congo", 'phone' => '242', 'iso2' => 'CG', 'iso3' => 'COG' ],
		'REU' => [ 'name' => "Reunion", 'phone' => '262', 'iso2' => 'RE', 'iso3' => 'REU' ],
		'ROU' => [ 'name' => "Romania", 'phone' => '40', 'iso2' => 'RO', 'iso3' => 'ROU' ],
		'RUS' => [ 'name' => "Russia", 'phone' => '7', 'iso2' => 'RU', 'iso3' => 'RUS' ],
		'RWA' => [ 'name' => "Rwanda", 'phone' => '250', 'iso2' => 'RW', 'iso3' => 'RWA' ],
		'BLM' => [ 'name' => "Saint Barthelemy", 'phone' => '590', 'iso2' => 'BL', 'iso3' => 'BLM' ],
		'SHN' => [ 'name' => "Saint Helena", 'phone' => '290', 'iso2' => 'SH', 'iso3' => 'SHN' ],
		'KNA' => [ 'name' => "Saint Kitts and Nevis", 'phone' => '1-869', 'iso2' => 'KN', 'iso3' => 'KNA' ],
		'LCA' => [ 'name' => "Saint Lucia", 'phone' => '1-758', 'iso2' => 'LC', 'iso3' => 'LCA' ],
		'MAF' => [ 'name' => "Saint Martin", 'phone' => '590', 'iso2' => 'MF', 'iso3' => 'MAF' ],
		'SPM' => [ 'name' => "Saint Pierre and Miquelon", 'phone' => '508', 'iso2' => 'PM', 'iso3' => 'SPM' ],
		'VCT' => [ 'name' => "Saint Vincent and the Grenadines", 'phone' => '1-784', 'iso2' => 'VC', 'iso3' => 'VCT' ],
		'WSM' => [ 'name' => "Samoa", 'phone' => '685', 'iso2' => 'WS', 'iso3' => 'WSM' ],
		'SMR' => [ 'name' => "San Marino", 'phone' => '378', 'iso2' => 'SM', 'iso3' => 'SMR' ],
		'STP' => [ 'name' => "Sao Tome and Principe", 'phone' => '239', 'iso2' => 'ST', 'iso3' => 'STP' ],
		'SAU' => [ 'name' => "Saudi Arabia", 'phone' => '966', 'iso2' => 'SA', 'iso3' => 'SAU' ],
		'SEN' => [ 'name' => "Senegal", 'phone' => '221', 'iso2' => 'SN', 'iso3' => 'SEN' ],
		'SRB' => [ 'name' => "Serbia", 'phone' => '381', 'iso2' => 'RS', 'iso3' => 'SRB' ],
		'SYC' => [ 'name' => "Seychelles", 'phone' => '248', 'iso2' => 'SC', 'iso3' => 'SYC' ],
		'SLE' => [ 'name' => "Sierra Leone", 'phone' => '232', 'iso2' => 'SL', 'iso3' => 'SLE' ],
		'SGP' => [ 'name' => "Singapore", 'phone' => '65', 'iso2' => 'SG', 'iso3' => 'SGP' ],
		'SXM' => [ 'name' => "Sint Maarten", 'phone' => '1-721', 'iso2' => 'SX', 'iso3' => 'SXM' ],
		'SVK' => [ 'name' => "Slovakia", 'phone' => '421', 'iso2' => 'SK', 'iso3' => 'SVK' ],
		'SVN' => [ 'name' => "Slovenia", 'phone' => '386', 'iso2' => 'SI', 'iso3' => 'SVN' ],
		'SLB' => [ 'name' => "Solomon Islands", 'phone' => '677', 'iso2' => 'SB', 'iso3' => 'SLB' ],
		'SOM' => [ 'name' => "Somalia", 'phone' => '252', 'iso2' => 'SO', 'iso3' => 'SOM' ],
		'ZAF' => [ 'name' => "South Africa", 'phone' => '27', 'iso2' => 'ZA', 'iso3' => 'ZAF' ],
		'KOR' => [ 'name' => "South Korea", 'phone' => '82', 'iso2' => 'KR', 'iso3' => 'KOR' ],
		'SSD' => [ 'name' => "South Sudan", 'phone' => '211', 'iso2' => 'SS', 'iso3' => 'SSD' ],
		'ESP' => [ 'name' => "Spain", 'phone' => '34', 'iso2' => 'ES', 'iso3' => 'ESP' ],
		'LKA' => [ 'name' => "Sri Lanka", 'phone' => '94', 'iso2' => 'LK', 'iso3' => 'LKA' ],
		'SDN' => [ 'name' => "Sudan", 'phone' => '249', 'iso2' => 'SD', 'iso3' => 'SDN' ],
		'SUR' => [ 'name' => "Suriname", 'phone' => '597', 'iso2' => 'SR', 'iso3' => 'SUR' ],
		'SJM' => [ 'name' => "Svalbard and Jan Mayen", 'phone' => '47', 'iso2' => 'SJ', 'iso3' => 'SJM' ],
		'SWZ' => [ 'name' => "Swaziland", 'phone' => '268', 'iso2' => 'SZ', 'iso3' => 'SWZ' ],
		'SWE' => [ 'name' => "Sweden", 'phone' => '46', 'iso2' => 'SE', 'iso3' => 'SWE' ],
		'CHE' => [ 'name' => "Switzerland", 'phone' => '41', 'iso2' => 'CH', 'iso3' => 'CHE' ],
		'SYR' => [ 'name' => "Syria", 'phone' => '963', 'iso2' => 'SY', 'iso3' => 'SYR' ],
		'TWN' => [ 'name' => "Taiwan", 'phone' => '886', 'iso2' => 'TW', 'iso3' => 'TWN' ],
		'TJK' => [ 'name' => "Tajikistan", 'phone' => '992', 'iso2' => 'TJ', 'iso3' => 'TJK' ],
		'TZA' => [ 'name' => "Tanzania", 'phone' => '255', 'iso2' => 'TZ', 'iso3' => 'TZA' ],
		'THA' => [ 'name' => "Thailand", 'phone' => '66', 'iso2' => 'TH', 'iso3' => 'THA' ],
		'TGO' => [ 'name' => "Togo", 'phone' => '228', 'iso2' => 'TG', 'iso3' => 'TGO' ],
		'TKL' => [ 'name' => "Tokelau", 'phone' => '690', 'iso2' => 'TK', 'iso3' => 'TKL' ],
		'TON' => [ 'name' => "Tonga", 'phone' => '676', 'iso2' => 'TO', 'iso3' => 'TON' ],
		'TTO' => [ 'name' => "Trinidad and Tobago", 'phone' => '1-868', 'iso2' => 'TT', 'iso3' => 'TTO' ],
		'TUN' => [ 'name' => "Tunisia", 'phone' => '216', 'iso2' => 'TN', 'iso3' => 'TUN' ],
		'TUR' => [ 'name' => "Turkey", 'phone' => '90', 'iso2' => 'TR', 'iso3' => 'TUR' ],
		'TKM' => [ 'name' => "Turkmenistan", 'phone' => '993', 'iso2' => 'TM', 'iso3' => 'TKM' ],
		'TCA' => [ 'name' => "Turks and Caicos Islands", 'phone' => '1-649', 'iso2' => 'TC', 'iso3' => 'TCA' ],
		'TUV' => [ 'name' => "Tuvalu", 'phone' => '688', 'iso2' => 'TV', 'iso3' => 'TUV' ],
		'VIR' => [ 'name' => "U.S. Virgin Islands", 'phone' => '1-340', 'iso2' => 'VI', 'iso3' => 'VIR' ],
		'UGA' => [ 'name' => "Uganda", 'phone' => '256', 'iso2' => 'UG', 'iso3' => 'UGA' ],
		'UKR' => [ 'name' => "Ukraine", 'phone' => '380', 'iso2' => 'UA', 'iso3' => 'UKR' ],
		'ARE' => [ 'name' => "United Arab Emirates", 'phone' => '971', 'iso2' => 'AE', 'iso3' => 'ARE' ],
		'GBR' => [ 'name' => "United Kingdom", 'phone' => '44', 'iso2' => 'GB', 'iso3' => 'GBR' ],
		'USA' => [ 'name' => "United States", 'phone' => '1', 'iso2' => 'US', 'iso3' => 'USA' ],
		'URY' => [ 'name' => "Uruguay", 'phone' => '598', 'iso2' => 'UY', 'iso3' => 'URY' ],
		'UZB' => [ 'name' => "Uzbekistan", 'phone' => '998', 'iso2' => 'UZ', 'iso3' => 'UZB' ],
		'VUT' => [ 'name' => "Vanuatu", 'phone' => '678', 'iso2' => 'VU', 'iso3' => 'VUT' ],
		'VAT' => [ 'name' => "Vatican", 'phone' => '379', 'iso2' => 'VA', 'iso3' => 'VAT' ],
		'VEN' => [ 'name' => "Venezuela", 'phone' => '58', 'iso2' => 'VE', 'iso3' => 'VEN' ],
		'VNM' => [ 'name' => "Vietnam", 'phone' => '84', 'iso2' => 'VN', 'iso3' => 'VNM' ],
		'WLF' => [ 'name' => "Wallis and Futuna", 'phone' => '681', 'iso2' => 'WF', 'iso3' => 'WLF' ],
		'ESH' => [ 'name' => "Western Sahara", 'phone' => '212', 'iso2' => 'EH', 'iso3' => 'ESH' ],
		'YEM' => [ 'name' => "Yemen", 'phone' => '967', 'iso2' => 'YE', 'iso3' => 'YEM' ],
		'ZMB' => [ 'name' => "Zambia", 'phone' => '260', 'iso2' => 'ZM', 'iso3' => 'ZMB' ],
		'ZWE' => [ 'name' => "Zimbabwe", 'phone' => '263', 'iso2' => 'ZW', 'iso3' => 'ZWE' ],
	);
        $dropdown_list = [];
	foreach( $cnlwdc as $char3 => $others ){
            $dropdown_list[$char3] = $others['name'];
        }
        return $dropdown_list;
} // EOF